name: Claude Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  claude-response:
    runs-on: ubuntu-latest
    # @claudeメンションが含まれている場合のみ実行
    if: |
      contains(github.event.comment.body || github.event.issue.body || github.event.pull_request.body || github.event.review.body, '@claude')
    
    steps:
      - name: Claude Code Action
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}